### ISSUE TITLE
selenium.common.exceptions.JavascriptException: Message: ReferenceError: Store is not defined

### ISSUE THREAD

**Issue by marcelocecin** [sidhusmart/WACAO#3]
hi there
I'm facing this error
selenium.common.exceptions.JavascriptException: Message: ReferenceError: Store is not defined
thank you

**Comment by sidhusmart** [comment]
Tested this and the issue exists. 

The root cause is that the underlying WebWhatsAPI that is used has changed. This calls fort he code to be refactored which will take a but of time.

You can check out the latest version of the Whatsapp API here for more information - https://github.com/mukulhase/WebWhatsapp-Wrapper
